name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # roda todo dia Ã  meia-noite
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ðŸ‘ˆ permite o bot fazer commit
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate snake animation
        uses: Platane/snk@v3
        with:
          github_user_name: GabrielCM12
          outputs: dist/github-contribution-grid-snake.svg
          palette: "blue"

      - name: Push snake animation to output branch
        run: |
          mkdir -p ./output
          cp dist/github-contribution-grid-snake.svg ./output/
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Generated snake animation" || echo "No changes to commit"
          git push origin HEAD:output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
